---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users":
    get:
      summary: Retrieves all users
      tags:
      - Users
      responses:
        '200':
          description: users found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
